import { RemoteConfig } from './types';

export const initialConfigs: RemoteConfig[] = [
  {
    id: '1',
    name: 'Welcome_message_V2',
    key: 'welcome_message_v2',
    description: 'Main Dashboard Welcome Title displayed to returning users after login.',
    status: 'STOPPED',
    type: 'String',
    version: 'v1.0',
    versionMajor: 1,
    versionMinor: 0,
    versionHistory: [
      { version: 'v1.0', status: 'STOPPED', date: '2026-02-10', author: 'John Smith', notes: 'Initial version, stopped after A/B test concluded.' },
    ],
    variantsCount: 2,
    rolloutPercentage: 100,
    hasGradualRollout: false,
    targetSegment: 'All Users',
    environment: 'Prod',
    lastEdited: '2 Hours ago',
    createdBy: 'John Smith',
    createdAt: '2026-02-01',
    usedInCampaign: true,
    keys: [
      {
        id: 'k1',
        name: 'greeting_title',
        dataType: 'String',
        defaultValue: 'Welcome back!',
        variants: [
          { id: 'v1', name: 'Control', value: 'Welcome back!', traffic: 50, isControl: true },
          { id: 'v2', name: 'Variant B', value: 'Good to see you again!', traffic: 50, isControl: false },
        ],
      },
    ],
  },
  {
    id: '2',
    name: 'Feature_flags_json',
    key: 'feature_flags_json',
    description: 'Configuration for experiment with feature flags passed as a JSON payload to mobile clients.',
    status: 'LIVE',
    type: 'JSON',
    version: 'v2.1',
    versionMajor: 2,
    versionMinor: 1,
    versionHistory: [
      { version: 'v1.0', status: 'COMPLETED', date: '2026-01-10', author: 'Jane Doe', notes: 'Initial rollout.' },
      { version: 'v2.0', status: 'STOPPED', date: '2026-01-25', author: 'Jane Doe', notes: 'Added new experiment flags.' },
      { version: 'v2.1', status: 'LIVE', date: '2026-02-15', author: 'Jane Doe', notes: 'Current live version with 3-way split.' },
    ],
    variantsCount: 3,
    rolloutPercentage: 75,
    hasGradualRollout: true,
    targetSegment: 'Premium Users',
    environment: 'Prod',
    lastEdited: '2 Hours ago',
    createdBy: 'Jane Doe',
    createdAt: '2026-01-10',
    usedInCampaign: false,
    keys: [
      {
        id: 'k2',
        name: 'feature_set',
        dataType: 'JSON',
        defaultValue: '{"newDashboard": false, "betaSearch": false}',
        variants: [
          { id: 'v3', name: 'Control', value: '{"newDashboard": false, "betaSearch": false}', traffic: 40, isControl: true },
          { id: 'v4', name: 'Variant B', value: '{"newDashboard": true, "betaSearch": false}', traffic: 30, isControl: false },
          { id: 'v5', name: 'Variant C', value: '{"newDashboard": true, "betaSearch": true}', traffic: 30, isControl: false },
        ],
      },
    ],
  },
  {
    id: '3',
    name: 'Max_retry_count',
    key: 'max_retry_count',
    description: 'API Failure Threshold Set for maximum retry attempts before showing error state to the user.',
    status: 'DRAFT',
    type: 'Integer',
    version: 'v1.0',
    versionMajor: 1,
    versionMinor: 0,
    versionHistory: [
      { version: 'v1.0', status: 'DRAFT', date: '2026-02-28', author: 'Bob Johnson', notes: 'Draft created.' },
    ],
    variantsCount: 2,
    rolloutPercentage: 0,
    hasGradualRollout: false,
    targetSegment: 'All Users',
    environment: 'Test',
    lastEdited: '2 Hours ago',
    createdBy: 'Bob Johnson',
    createdAt: '2026-02-28',
    usedInCampaign: false,
    keys: [
      {
        id: 'k3',
        name: 'retry_limit',
        dataType: 'Integer',
        defaultValue: '3',
        variants: [
          { id: 'v6', name: 'Control', value: '3', traffic: 50, isControl: true },
          { id: 'v7', name: 'Variant B', value: '5', traffic: 50, isControl: false },
        ],
      },
    ],
  },
  {
    id: '4',
    name: 'Promo_banner_enabled',
    key: 'promo_banner_enabled',
    description: 'Toggle for Black Friday Sale promotional banner visibility across all mobile platforms.',
    status: 'LIVE',
    type: 'Boolean',
    version: 'v1.2',
    versionMajor: 1,
    versionMinor: 2,
    versionHistory: [
      { version: 'v1.0', status: 'STOPPED', date: '2026-01-15', author: 'Alice Brown', notes: 'Initial test.' },
      { version: 'v1.1', status: 'STOPPED', date: '2026-02-01', author: 'Alice Brown', notes: 'Adjusted targeting.' },
      { version: 'v1.2', status: 'LIVE', date: '2026-02-20', author: 'Alice Brown', notes: 'Live for Black Friday campaign.' },
    ],
    variantsCount: 2,
    rolloutPercentage: 50,
    hasGradualRollout: true,
    targetSegment: 'New Users',
    environment: 'Prod',
    lastEdited: '2 Hours ago',
    createdBy: 'Alice Brown',
    createdAt: '2026-01-15',
    usedInCampaign: true,
    keys: [
      {
        id: 'k4',
        name: 'show_banner',
        dataType: 'Boolean',
        defaultValue: 'false',
        variants: [
          { id: 'v8', name: 'Control', value: 'false', traffic: 50, isControl: true },
          { id: 'v9', name: 'Variant B', value: 'true', traffic: 50, isControl: false },
        ],
      },
    ],
  },
  {
    id: '5',
    name: 'Dark_mode_rollout',
    key: 'dark_mode_rollout',
    description: 'Dark mode feature rollout completed after successful A/B test. Now fully deployed to all users.',
    status: 'COMPLETED',
    type: 'Boolean',
    version: 'v3.0',
    versionMajor: 3,
    versionMinor: 0,
    versionHistory: [
      { version: 'v1.0', status: 'STOPPED', date: '2025-10-01', author: 'Charlie Davis', notes: 'Initial 10% rollout.' },
      { version: 'v2.0', status: 'STOPPED', date: '2025-11-15', author: 'Charlie Davis', notes: '50% rollout test.' },
      { version: 'v3.0', status: 'COMPLETED', date: '2025-12-01', author: 'Charlie Davis', notes: 'Full rollout declared winner.' },
    ],
    variantsCount: 2,
    rolloutPercentage: 100,
    hasGradualRollout: false,
    targetSegment: 'All Users',
    environment: 'Prod',
    lastEdited: '3 days ago',
    createdBy: 'Charlie Davis',
    createdAt: '2025-10-01',
    usedInCampaign: false,
    keys: [
      {
        id: 'k5',
        name: 'dark_mode_enabled',
        dataType: 'Boolean',
        defaultValue: 'true',
        variants: [
          { id: 'v10', name: 'Control', value: 'false', traffic: 0, isControl: true },
          { id: 'v11', name: 'Winner', value: 'true', traffic: 100, isControl: false },
        ],
      },
    ],
  },
  {
    id: '6',
    name: 'Onboarding_flow_v3',
    key: 'onboarding_flow_v3',
    description: 'New user onboarding flow experiment testing 3 different sequences for improved activation rate.',
    status: 'DRAFT',
    type: 'JSON',
    version: 'v1.0',
    versionMajor: 1,
    versionMinor: 0,
    versionHistory: [
      { version: 'v1.0', status: 'DRAFT', date: '2026-03-01', author: 'Diana Prince', notes: 'Draft for new onboarding flow.' },
    ],
    variantsCount: 3,
    rolloutPercentage: 0,
    hasGradualRollout: false,
    targetSegment: 'New Users',
    environment: 'Test',
    lastEdited: '1 day ago',
    createdBy: 'Diana Prince',
    createdAt: '2026-03-01',
    usedInCampaign: false,
    keys: [
      {
        id: 'k6',
        name: 'flow_config',
        dataType: 'JSON',
        defaultValue: '{"steps": ["welcome", "profile", "tutorial"], "skipable": false}',
        variants: [
          { id: 'v12', name: 'Control', value: '{"steps": ["welcome", "profile", "tutorial"], "skipable": false}', traffic: 34, isControl: true },
          { id: 'v13', name: 'Short Flow', value: '{"steps": ["welcome", "tutorial"], "skipable": true}', traffic: 33, isControl: false },
          { id: 'v14', name: 'Gamified', value: '{"steps": ["welcome", "quiz", "profile", "reward"], "skipable": false}', traffic: 33, isControl: false },
        ],
      },
    ],
  },
  {
    id: '7',
    name: 'Search_algorithm_weight',
    key: 'search_algorithm_weight',
    description: 'Search ranking algorithm weight configuration to test different relevance scoring models.',
    status: 'STOPPED',
    type: 'Integer',
    version: 'v2.0',
    versionMajor: 2,
    versionMinor: 0,
    versionHistory: [
      { version: 'v1.0', status: 'STOPPED', date: '2026-01-20', author: 'Eve Wilson', notes: 'Initial algorithm test.' },
      { version: 'v2.0', status: 'STOPPED', date: '2026-02-10', author: 'Eve Wilson', notes: 'Updated with new weights, stopped pending review.' },
    ],
    variantsCount: 2,
    rolloutPercentage: 0,
    hasGradualRollout: false,
    targetSegment: 'Power Users',
    environment: 'Prod',
    lastEdited: '5 days ago',
    createdBy: 'Eve Wilson',
    createdAt: '2026-01-20',
    usedInCampaign: false,
    keys: [
      {
        id: 'k7',
        name: 'relevance_weight',
        dataType: 'Integer',
        defaultValue: '70',
        variants: [
          { id: 'v15', name: 'Control', value: '70', traffic: 50, isControl: true },
          { id: 'v16', name: 'High Relevance', value: '90', traffic: 50, isControl: false },
        ],
      },
    ],
  },
];
